In [1]:
print ('Hello World')

Hello World


In [2]:
l=[1,2,3,4]

In [3]:
#this a comment 

In [4]:
'''
This is for larger comments
'''

'\nThis is for larger comments\n'

This is a Markdown cell

This will not run as code!

CREATING ARRAYS

In [5]:
import numpy as np

In [6]:
my_list1 = [1,2,3,4]

In [7]:
my_array1 = np.array(my_list1)

In [8]:
my_array1

array([1, 2, 3, 4])

In [9]:
my_list2 = [11,22,33,44]

In [10]:
my_lists = [my_list1,my_list2]

In [11]:
my_lists

[[1, 2, 3, 4], [11, 22, 33, 44]]

In [12]:
my_array2 = np.array(my_lists)

In [13]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [14]:
#Knowing the dimension of the array
my_array2.shape

(2, 4)

In [15]:
#Knowing the datatype of the array
my_array2.dtype

dtype('int64')

In [16]:
#special case arrays
#Array of all zeros
my_zeros_array = np.zeros(5)

In [17]:
my_zeros_array.shape

(5,)

In [18]:
my_zeros_array

array([ 0.,  0.,  0.,  0.,  0.])

In [19]:
my_zeros_array.dtype

dtype('float64')

In [20]:
np.zeros([5,5])

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [21]:
np.ones([5,4])

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [22]:
np.empty(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [23]:
np.empty(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [24]:
#creating identity matrix
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [25]:
np.arange(5,50,2,dtype=int)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])

In [26]:
np.arange(5,30,2,dtype=float)

array([  5.,   7.,   9.,  11.,  13.,  15.,  17.,  19.,  21.,  23.,  25.,
        27.,  29.])

In [27]:
np.arange(5)

array([0, 1, 2, 3, 4])

USNG ARRAYS AND SCALARS

In [28]:
5/2

2.5

In [29]:
arr1 = np.array([[1,2,3,4],[8,9,10,11]])

In [30]:
arr1

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [31]:
arr1.shape

(2, 4)

In [32]:
#element to element multiplication
arr1*arr1

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [33]:
#subtraction
arr1-arr1

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [34]:
#operation with scalars
1/arr1

array([[ 1.        ,  0.5       ,  0.33333333,  0.25      ],
       [ 0.125     ,  0.11111111,  0.1       ,  0.09090909]])

In [35]:
#exponential
arr1 ** 2

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

INDEXING ARRAYS

In [36]:
arr = np.arange(0,11)

In [37]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
arr[1:5]

array([1, 2, 3, 4])

In [39]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [40]:
#Setting first five numbers in the array to 100
arr[0:5] = 100

In [41]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [42]:
slice_of_arr = arr[0:6]
slice_of_arr

array([100, 100, 100, 100, 100,   5])

In [43]:
slice_of_arr [:] =99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

slice_of_arr is just a view of the original array arr. So any changes in slice_of arr will reflect in arr. This avoids memory issue (not many copies of the same array in the memory issue)

In [44]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

If we want a copy of the array then we have to be explicit

In [45]:
arr_copy = arr.copy()

In [46]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Indexing in 2D array

In [47]:
arr_2d = np.array ([[5,10,15],
                    [20,25,30],
                    [35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

Notes: Indexing in Python starts from 0

In [48]:
arr_2d[1]

array([20, 25, 30])

In [49]:
arr_2d[0]

array([ 5, 10, 15])

To print the exact element in array specify the row and column number of that element

In [50]:
arr_2d[1][0]

20

To extract a 2x2 array from the original array

In [51]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [52]:
arr_2d[1,0]

20

Fancy Indexing

In [53]:
arr2d = np.zeros((10,10))

In [54]:
arr2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [55]:
arr_length = arr2d.shape[1]

In [56]:
arr_length

10

In [57]:
for i in range(arr_length):
    arr2d[i] =1

In [58]:
arr2d

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [59]:
for i in range(arr_length):
    arr2d[i] =i

In [60]:
arr2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.]])

In [61]:
arr2d[[2,4,6,8]]

array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.]])

In [62]:
#indexing can be in any order
arr2d[[6,4,2,8]]

array([[ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.]])

ARRAY TRANSPOSITION

In [63]:
#creating an array with 50 points and size 10X5
arr1 = np.arange(50).reshape((10,5))
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [64]:
#Transposing the array
arr1.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49]])

In [65]:
#printing the dot product
np.dot(arr1.T,arr1)

array([[7125, 7350, 7575, 7800, 8025],
       [7350, 7585, 7820, 8055, 8290],
       [7575, 7820, 8065, 8310, 8555],
       [7800, 8055, 8310, 8565, 8820],
       [8025, 8290, 8555, 8820, 9085]])

In [66]:
#For 3D array
arr3d = np.arange(50).reshape((5,5,2))
arr3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]]])

In [67]:
arr3d.transpose((1,0,2))

array([[[ 0,  1],
        [10, 11],
        [20, 21],
        [30, 31],
        [40, 41]],

       [[ 2,  3],
        [12, 13],
        [22, 23],
        [32, 33],
        [42, 43]],

       [[ 4,  5],
        [14, 15],
        [24, 25],
        [34, 35],
        [44, 45]],

       [[ 6,  7],
        [16, 17],
        [26, 27],
        [36, 37],
        [46, 47]],

       [[ 8,  9],
        [18, 19],
        [28, 29],
        [38, 39],
        [48, 49]]])

swapping axes

In [68]:
#1X3 array
arr2 = np.array([[1,2,3]])
arr2

array([[1, 2, 3]])

In [69]:
#swapped to 3X1 array
arr2.swapaxes(0,1)

array([[1],
       [2],
       [3]])